"""empty message

Revision ID: 1092ab6d4f22
Revises: a0777741dee6
Create Date: 2016-11-30 15:24:51.131893

"""

# revision identifiers, used by Alembic.
revision = '1092ab6d4f22'
down_revision = 'a0777741dee6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.String(length=2), nullable=True))
        batch_op.drop_column('private_full_name')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_full_name', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('locale')

    ### end Alembic commands ###
