"""drop non-translated Action fields

Revision ID: 16104ac821d5
Revises: 8b57e757256c
Create Date: 2017-04-18 14:08:33.290068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16104ac821d5'
down_revision = '8b57e757256c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes_action', schema=None) as batch_op:
        batch_op.drop_column('_summary')
        batch_op.drop_column('_title')
        batch_op.drop_column('_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('_title', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('_summary', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
