"""add Action.image, update Cause & Action translation FKs

Revision ID: 1944900d3b2c
Revises: b4a2fcb7edf8
Create Date: 2017-08-22 16:22:37.960641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1944900d3b2c'
down_revision = 'b4a2fcb7edf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))

    with op.batch_alter_table('causes_action_translation', schema=None) as batch_op:
        batch_op.drop_constraint(u'fk_causes_action_translation_id_causes_action', type_='foreignkey')
        batch_op.create_foreign_key(None, 'causes_action', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('causes_cause_translation', schema=None) as batch_op:
        batch_op.drop_constraint(u'fk_causes_cause_translation_id_causes_cause', type_='foreignkey')
        batch_op.create_foreign_key(None, 'causes_cause', ['id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes_cause_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(u'fk_causes_cause_translation_id_causes_cause', 'causes_cause', ['id'], ['id'])

    with op.batch_alter_table('causes_action_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(u'fk_causes_action_translation_id_causes_action', 'causes_action', ['id'], ['id'])

    with op.batch_alter_table('causes_action', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
