"""add Cause translations

Revision ID: 2d56302e6e24
Revises: 8321545d47fa
Create Date: 2017-04-18 00:26:26.710903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d56302e6e24'
down_revision = '8321545d47fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes_cause_translation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('intro', sa.String(length=180), nullable=True),
    sa.Column('story_heading', sa.String(length=128), nullable=True),
    sa.Column('story_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['causes_cause.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    with op.batch_alter_table(u'causes_cause', schema=None) as batch_op:
        batch_op.alter_column('story_content', new_column_name='_story_content')
        batch_op.alter_column('story_heading', new_column_name='_story_heading')
        batch_op.alter_column('title', new_column_name='_title')
        batch_op.alter_column('intro', new_column_name='_intro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'causes_cause', schema=None) as batch_op:
        batch_op.alter_column('_title', new_column_name='title')
        batch_op.alter_column('_intro', new_column_name='intro')
        batch_op.alter_column('_story_heading', new_column_name='story_heading')
        batch_op.alter_column('_story_content', new_column_name='story_content')

    op.drop_table('causes_cause_translation')
    # ### end Alembic commands ###
