"""empty message

Revision ID: 4859392ce443
Revises: d0d52151b3b5
Create Date: 2016-11-11 12:10:58.615832

"""

# revision identifiers, used by Alembic.
revision = '4859392ce443'
down_revision = 'd0d52151b3b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('causes_action') as b_op:
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
    with op.batch_alter_table('causes_cause') as b_op:
        b_op.alter_column('slug',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
    with op.batch_alter_table('discussions_post') as b_op:
        b_op.alter_column('body',
                   existing_type=sa.TEXT(),
                   nullable=False)
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
    with op.batch_alter_table('pages_page') as b_op:
        b_op.alter_column('content',
                   existing_type=sa.TEXT(),
                   nullable=False)
        b_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
        b_op.alter_column('url',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=False)
    with op.batch_alter_table('users_user') as b_op:
        b_op.create_unique_constraint('social_id', ['social_id'])
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=False)
    op.create_index(op.f('ix_users_user_employer'), 'users_user', ['employer'], unique=False)
    op.create_index(op.f('ix_users_user_nickname'), 'users_user', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_user_phone'), 'users_user', ['phone'], unique=False)
    op.create_index(op.f('ix_users_user_zip'), 'users_user', ['zip'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user') as b_op:
        b_op.drop_constraint('social_id', type_='unique')
    op.drop_index(op.f('ix_users_user_zip'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_phone'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_employer'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    with op.batch_alter_table('pages_page') as b_op:
        b_op.alter_column('url',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
        b_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
        b_op.alter_column('content',
                   existing_type=sa.TEXT(),
                   nullable=True)
    with op.batch_alter_table('discussions_post') as b_op:
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
        b_op.alter_column('body',
                   existing_type=sa.TEXT(),
                   nullable=True)
    with op.batch_alter_table('causes_cause') as b_op:
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
        b_op.alter_column('slug',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
    with op.batch_alter_table('causes_action') as b_op:
        b_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=128),
                   nullable=True)
    ### end Alembic commands ###
