"""empty message

Revision ID: 600224b21ce1
Revises: 1092ab6d4f22
Create Date: 2017-02-13 19:08:57.892448

"""

# revision identifiers, used by Alembic.
revision = '600224b21ce1'
down_revision = '1092ab6d4f22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_table('migration_tmp')
    with op.batch_alter_table('log_event_types', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_name', ['name'])

    with op.batch_alter_table('log_events', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'log_event_types', ['event_type_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_email'))
        batch_op.create_index('ix_users_user_email', ['email'], unique=False)

    with op.batch_alter_table('log_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('log_event_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('migration_tmp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('social_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('initials', sa.VARCHAR(length=8), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('employer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('private_full_name', sa.BOOLEAN(), nullable=True),
    sa.Column('zip', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    ### end Alembic commands ###
