"""empty message

Revision ID: 8321545d47fa
Revises: e21949ae489f
Create Date: 2017-04-17 22:03:29.747203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8321545d47fa'
down_revision = 'e21949ae489f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_nickname'), ['nickname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_zip'), ['zip'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_zip'))
        batch_op.drop_index(batch_op.f('ix_users_user_nickname'))

    # ### end Alembic commands ###
