"""empty message

Revision ID: a0777741dee6
Revises: 4859392ce443
Create Date: 2016-11-12 01:10:27.991539

"""

# revision identifiers, used by Alembic.
revision = 'a0777741dee6'
down_revision = '4859392ce443'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pages_page_i18n = op.create_table('pages_page_i18n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pages_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )

    conn = op.get_bind()
    res = conn.execute("select id, name, content from pages_page")
    results = res.fetchall()
    pages = [
        {
            'id': r[0], 
            'name': r[1], 
            'content': r[2], 
            'locale': 'en', 
        } 
        for r in results
    ]
    op.bulk_insert(pages_page_i18n, pages)

    with op.batch_alter_table(u'pages_page', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('name')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'pages_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))

    op.drop_table('pages_page_i18n')
    ### end Alembic commands ###
