"""empty message

Revision ID: b4a2fcb7edf8
Revises: 4a490dacaa06
Create Date: 2017-04-18 17:10:40.796438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a2fcb7edf8'
down_revision = '4a490dacaa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_page', schema=None) as batch_op:
        batch_op.drop_column('_content')
        batch_op.drop_column('_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_name', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('_content', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
