"""add Comment.deleted

Revision ID: c6f5a4b7a379
Revises: bd4c184c15f7
Create Date: 2018-04-25 14:35:32.604190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f5a4b7a379'
down_revision = 'bd4c184c15f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions_comment', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
