"""empty message

Revision ID: d0d52151b3b5
Revises: None
Create Date: 2016-11-11 12:03:02.609805

"""

# revision identifiers, used by Alembic.
revision = 'd0d52151b3b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('boss', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('story_heading', sa.String(length=128), nullable=True),
    sa.Column('story_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('initials', sa.String(length=8), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('employer', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('private_full_name', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=False)
    op.create_index(op.f('ix_users_user_employer'), 'users_user', ['employer'], unique=False)
    op.create_index(op.f('ix_users_user_nickname'), 'users_user', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_user_phone'), 'users_user', ['phone'], unique=False)
    op.create_index(op.f('ix_users_user_zip'), 'users_user', ['zip'], unique=False)
    op.create_table('causes_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causes_cause_creators',
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('causes_cause_supporters',
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('causes_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussions_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causes_action_supporters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['causes_action.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('discussions_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['discussions_post.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['discussions_comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussions_comment')
    op.drop_table('causes_action_supporters')
    op.drop_table('discussions_post')
    op.drop_table('causes_demand')
    op.drop_table('causes_cause_supporters')
    op.drop_table('causes_cause_creators')
    op.drop_table('causes_action')
    op.drop_index(op.f('ix_users_user_zip'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_phone'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_employer'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    op.drop_table('users_user')
    op.drop_table('pages_page')
    op.drop_table('causes_cause')
    ### end Alembic commands ###
