"""empty message

Revision ID: e21949ae489f
Revises: 
Create Date: 2017-04-17 21:54:17.907405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21949ae489f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('boss', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('intro', sa.Text(length=180), nullable=True),
    sa.Column('video', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('story_heading', sa.String(length=128), nullable=True),
    sa.Column('story_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pages_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('initials', sa.String(length=8), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('employer', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_employer'), ['employer'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_nickname'), ['nickname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_zip'), ['zip'], unique=False)

    op.create_table('causes_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causes_cause_creators',
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('causes_cause_supporters',
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('causes_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussions_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['causes_cause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Unicode(length=255), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['log_event_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causes_action_supporters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['causes_action.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], )
    )
    op.create_table('discussions_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['discussions_post.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['discussions_comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussions_comment')
    op.drop_table('causes_action_supporters')
    op.drop_table('log_events')
    op.drop_table('discussions_post')
    op.drop_table('causes_demand')
    op.drop_table('causes_cause_supporters')
    op.drop_table('causes_cause_creators')
    op.drop_table('causes_action')
    with op.batch_alter_table('users_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_zip'))
        batch_op.drop_index(batch_op.f('ix_users_user_phone'))
        batch_op.drop_index(batch_op.f('ix_users_user_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_user_employer'))
        batch_op.drop_index(batch_op.f('ix_users_user_email'))

    op.drop_table('users_user')
    op.drop_table('pages_page')
    op.drop_table('log_event_types')
    op.drop_table('causes_cause')
    # ### end Alembic commands ###
