"""add Action translations

Revision ID: f4984bdb99ec
Revises: d568eda603db
Create Date: 2017-04-18 13:13:42.620950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4984bdb99ec'
down_revision = 'd568eda603db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes_action_translation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['causes_action.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    with op.batch_alter_table(u'causes_action', schema=None) as batch_op:
        batch_op.alter_column('summary', new_column_name='_summary')
        batch_op.alter_column('description', new_column_name='_description')
        batch_op.alter_column('title', new_column_name='_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'causes_action', schema=None) as batch_op:
        batch_op.alter_column('_summary', new_column_name='summary')
        batch_op.alter_column('_description', new_column_name='description')
        batch_op.alter_column('_title', new_column_name='title')

    op.drop_table('causes_action_translation')
    # ### end Alembic commands ###
