"""empty message

Revision ID: f992c0df5662
Revises: 16104ac821d5
Create Date: 2017-04-18 17:01:31.123179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f992c0df5662'
down_revision = '16104ac821d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_page_translation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pages_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    with op.batch_alter_table(u'pages_page', schema=None) as batch_op:
        batch_op.alter_column('content', new_column_name='_content')
        batch_op.alter_column('name', new_column_name='_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'pages_page', schema=None) as batch_op:
        batch_op.alter_column('_content', new_column_name='content')
        batch_op.alter_column('_name', new_column_name='name')

    op.drop_table('pages_page_translation')
    # ### end Alembic commands ###
